import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/context/authContext";

export const metadata: Metadata = {
  title: "Unite",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter"> 
        <body className={`${inter.className} antialiased`}>
          <AuthProvider>
          {children}
          </AuthProvider>
      </body>
    </html>
  );
}
